### ISSUE TITLE
Allow AWS credentials (`aws_access_key_id` and `aws_secret_access_key`)

### ISSUE THREAD

**Issue by benjaminch** [Qovery/iam-eks-user-mapper#17]
**Context**
As of today, the tool requires a role based AWS credentials to works. It would be nice to allow to work via AWS credentials (`aws_access_key_id` and `aws_secret_access_key`) if one doesn't need a role based configuration.

**Definition of done**
- chart to support those two new fields as values [here](https://github.com/Qovery/iam-eks-user-mapper/blob/main/charts/iam-eks-user-mapper/values.yaml#L8) 
- add those as program args in clap [here](https://github.com/Qovery/iam-eks-user-mapper/blob/main/src/main.rs#L20)
- add those in program configuration [here](https://github.com/Qovery/iam-eks-user-mapper/blob/main/src/config.rs#L51)
- make sure the program can run without role specified if credentials are provided

**Comment by mmoreiradj** [comment]
Hey @benjaminch is this still relevant ? I'm willing to work on it.

**Comment by benjaminch** [comment]
Hey @mmoreiradj,

Of course it's still relevant !

Thanks for your help 🙏

**Comment by mmoreiradj** [comment]
Hey @benjaminch ! Could you take a quick look at the PR I submitted?

**Comment by benjaminch** [comment]
Hey @mmoreiradj !
Thanks a lot for this contribution.
I have dropped couple comments.

**Comment by benjaminch** [comment]
Done [here](https://github.com/Qovery/iam-eks-user-mapper/pull/36)
